export const COLS = [
  {
    name: "The Favourites", color: "#378ADD",
    g: [
      { name: "Scottie Scheffler", odds: "5/1", fact: "World No.1 and defending champion — the man to beat at Augusta. Won here in 2022 and 2024, he's turned this course into a personal playground." },
      { name: "Bryson DeChambeau", odds: "10/1", fact: "Runner-up in 2023, he reshapes courses with his power game. His iron play has improved dramatically and Augusta's par 5s are his bread and butter." },
      { name: "Jon Rahm", odds: "10/1", fact: "Won The Masters in 2023 with a dominant final round. His aggressive, ball-striking game suits Augusta perfectly — expect him to be in contention on Sunday." },
      { name: "Rory McIlroy", odds: "12/1", fact: "The career Grand Slam remains elusive but he finally broke through in 2025. Now a Masters champion, the monkey is off his back and he arrives as a genuine threat." },
      { name: "Xander Schauffele", odds: "16/1", fact: "A major champion who tends to go deep at Augusta. His ball-striking statistics rank among the world's best and he handles pressure rounds with composure." },
      { name: "Ludvig Åberg", odds: "16/1", fact: "One of the most exciting ball-strikers in world golf. Was runner-up on Masters debut — Augusta suits his game and he has unfinished business here." },
      { name: "Matt Fitzpatrick", odds: "22/1", fact: "US Open champion whose precise iron play is tailor-made for Augusta's back nine. Consistently finishes in the top 20 here and is overdue a big week." },
      { name: "Cameron Young", odds: "22/1", fact: "A long hitter with a deft short game — exactly the profile Augusta rewards. Multiple top-10 finishes in majors suggest a breakthrough is coming." },
      { name: "Tommy Fleetwood", odds: "22/1", fact: "A consummate ball-striker who has been knocking on the door at Augusta for years. His iron play on the back nine could be the difference maker." },
      { name: "Justin Rose", odds: "30/1", fact: "2013 Masters runner-up and perennial Augusta contender. His experience around these greens is invaluable and he tends to peak for major championships." },
      { name: "Robert MacIntyre", odds: "33/1", fact: "Scottish left-hander who hits it long and shapes shots both ways. His wedge game is elite and Augusta's undulating greens suit his imaginative short game." },
      { name: "Patrick Reed", odds: "33/1", fact: "The 2018 Masters champion who thrives in the big moment. Reed knows how to win at Augusta and his short game around Amen Corner remains world-class." },
      { name: "Collin Morikawa", odds: "35/1", fact: "Two-time major champion who has been rebuilding his game. When his irons are on song, Morikawa can dismantle any course — including Augusta National." },
      { name: "Hideki Matsuyama", odds: "40/1", fact: "The 2021 Masters champion who is adored by Augusta's galleries. His driving accuracy and iron play are perfectly suited to the demands of Augusta National." },
      { name: "Jordan Spieth", odds: "40/1", fact: "Won in 2015, runner-up in 2014 and 2016 — Augusta suits him like a glove. His wizardry around the greens and course knowledge make him dangerous every year." },
    ]
  },
  {
    name: "The Could Do's", color: "#BA7517",
    g: [
      { name: "Brooks Koepka", odds: "40/1", fact: "Four-time major champion who elevates his game on the biggest stages. His ball-striking off the tee is elite and he has the mental fortitude to win at Augusta." },
      { name: "Min Woo Lee", odds: "40/1", fact: "Freewheeling Australian with serious power and creativity. His fearless approach to shot-making could be a real asset around Augusta's unique challenges." },
      { name: "Si Woo Kim", odds: "45/1", fact: "A multiple PGA Tour winner with solid course management. His putting on Bermuda grass — which Augusta's greens feature — is quietly one of his strengths." },
      { name: "Chris Gotterup", odds: "50/1", fact: "Long hitter who earned his Masters debut through strong Tour form. An unknown quantity at Augusta but power players can take the course by surprise." },
      { name: "Viktor Hovland", odds: "50/1", fact: "The Norwegian has improved his wedge game significantly. His ball-striking is world-class and a full week at Augusta should suit his creative, attacking style." },
      { name: "Russell Henley", odds: "55/1", fact: "A quietly consistent performer on Tour who rarely makes headlines but regularly contends. His iron play is in the top tier and Augusta rewards that above all." },
      { name: "Shane Lowry", odds: "60/1", fact: "The Irishman is a frontrunner who thrives on pressure — as his Portrush win proved. His power and creativity make him a genuine sleeper pick at Augusta." },
      { name: "Akshay Bhatia", odds: "60/1", fact: "One of the most naturally talented young players on Tour. His shotmaking is exceptional and he's shown no fear at big events — a potential surprise package." },
      { name: "Adam Scott", odds: "65/1", fact: "The 2013 Masters champion who still has one of the most beautiful swings in golf. Augusta holds special meaning for Scott and he always shows up here." },
      { name: "Justin Thomas", odds: "65/1", fact: "Two-time major champion who has been finding form. JT's combination of distance and precision suits Augusta, and he's overdue a deep run at the Masters." },
      { name: "Sepp Straka", odds: "70/1", fact: "An Austrian with a solid, reliable game who rarely makes big mistakes. His iron play off the tee is excellent and Augusta rewards players who hit fairways." },
      { name: "Tyrrell Hatton", odds: "70/1", fact: "A highly combustible character whose game peaks when the fire is channelled right. Has a top-10 at Augusta and knows the course well — temper permitting." },
      { name: "Patrick Cantlay", odds: "70/1", fact: "One of the most analytically sharp players in the game. Cantlay's meticulous approach to course management and putting make Augusta a great fit." },
      { name: "Jason Day", odds: "70/1", fact: "A former world No.1 experiencing a career resurgence. His bunker play and short game are exceptional and Augusta's sand traps make that especially valuable." },
      { name: "Jake Knapp", odds: "80/1", fact: "PGA Tour winner with a raw, powerful game. Augusta on debut is tough but long hitters who can also putt have historically surprised at this venue." },
    ]
  },
  {
    name: "The Possible's", color: "#1D9E75",
    g: [
      { name: "Jacob Bridgeman", odds: "80/1", fact: "Promising young player with a clean ball-striking game. A long shot, but Augusta has a history of rewarding debutants who don't know to be scared." },
      { name: "Marco Penge", odds: "80/1", fact: "European Tour standout making his Augusta debut. The Englishman is a solid iron player — if the nerves settle, he could make the cut and more." },
      { name: "Sungjae Im", odds: "100/1", fact: "A model of consistency — rarely blows up but rarely catches fire either. His steady, mistake-free game could produce a quiet but respectable week at Augusta." },
      { name: "Sam Burns", odds: "100/1", fact: "Multiple Tour winner with excellent putting stats. If his iron play clicks for a full week, Burns has the scoring ability to post a surprise low number." },
      { name: "Harris English", odds: "100/1", fact: "Tour veteran who finds Augusta's pace of play and course setup suits his methodical approach. Has made the cut here multiple times and knows the track." },
      { name: "Corey Conners", odds: "100/1", fact: "One of the most accurate drivers on Tour — and Augusta rewards fairways above almost everything else. A steady, reliable pick who could quietly go deep." },
      { name: "J.J. Spaun", odds: "100/1", fact: "Confident Tour winner who has shown he can handle pressure rounds. His game is built on ball-striking and that's exactly what Augusta demands." },
      { name: "Cameron Smith", odds: "100/1", fact: "The 2022 Masters runner-up with one of the best putting strokes in the world. If his irons are firing, Smith absolutely has the game to win this tournament." },
      { name: "Nicolai Højgaard", odds: "100/1", fact: "Danish twin brother of Rasmus, he's the slightly higher-ranked of the two. His creativity and power suit Augusta and he's been in excellent form." },
      { name: "Maverick McNealy", odds: "100/1", fact: "Stanford-educated with an ultra-consistent game. McNealy rarely makes mistakes and that keep-it-in-play strategy tends to pay dividends at Augusta." },
      { name: "Gary Woodland", odds: "100/1", fact: "US Open champion with serious power. Augusta's par 5s are gettable for a player of his length, and he has the experience to manage a major week." },
      { name: "Max Homa", odds: "100/1", fact: "Multiple Tour winner with an engaging game and excellent social media — but also genuinely elite iron play when he's at his best." },
      { name: "Daniel Berger", odds: "125/1", fact: "A player who has spent several years rebuilding after injury. When healthy he's a top-10 player in the world — if he's found his game, this price is generous." },
      { name: "Ben Griffin", odds: "125/1", fact: "Rising Tour player with a solid all-round game. Augusta may come a bit soon but he has the talent to make the cut and cause a minor shock." },
      { name: "Rasmus Højgaard", odds: "150/1", fact: "Danish twin who has been impressive on the European Tour. His ballstriking is excellent and at 150/1, he's an interesting outsider play." },
      { name: "Kurt Kitayama", odds: "150/1", fact: "Tour winner at Valspar who showed he can handle pressure. A grinder who makes few bogeys — exactly the profile that can sneak into the top 20 at Augusta." },
    ]
  },
  {
    name: "The Bubble (Cut?)", color: "#888780",
    g: [
      { name: "Aaron Rai", odds: "150/1", fact: "English ball-striker who earned his debut through strong European Tour form. The cut line at Augusta typically falls around +4 — Rai has the game to make it." },
      { name: "Wyndham Clark", odds: "150/1", fact: "US Open champion at Pebble Beach who proved he can win big. His fearless attitude is an asset but Augusta demands patience too — an intriguing mix." },
      { name: "Ryan Gerard", odds: "150/1", fact: "Young Tour player with a raw, attacking game. Augusta is tough on first-timers but Gerard's power gives him birdie chances on the par 5s." },
      { name: "Brian Harman", odds: "150/1", fact: "The 2023 Open champion who plays with remarkable accuracy. His reliable left-to-right ball flight suits Augusta's design and he rarely blows up." },
      { name: "Sam Stevens", odds: "175/1", fact: "Emerging Tour talent with an impressive record for his age. Augusta is a big ask but Stevens is a name to watch across the next decade of majors." },
      { name: "Max Greyserman", odds: "175/1", fact: "A consistent ball-striker who tends to make cuts rather than miss them. At 175/1, making the weekend would be a decent result — winning would be seismic." },
      { name: "Ryan Fox", odds: "175/1", fact: "Long-hitting New Zealander who has been in strong form on the European Tour. Augusta suits power players and Fox is one of the longer hitters in the field." },
      { name: "Jarvis Casey", odds: "175/1", fact: "Amateur or recent Tour card holder making his Augusta bow. The experience of playing Augusta National itself will be the story — anything else is a bonus." },
      { name: "Keegan Bradley", odds: "175/1", fact: "US Ryder Cup captain with a solid pedigree. Playing Augusta while captaining the Ryder Cup team adds extra motivation — and Bradley is a proven major contender." },
      { name: "Haotong Li", odds: "175/1", fact: "Chinese star with power and flair. Li is capable of brilliant rounds but also inconsistent ones — the cut may hinge on which version turns up on Thursday." },
      { name: "Dustin Johnson", odds: "175/1", fact: "The 2020 Masters champion with one of the game's great ball-striking records at Augusta. Even at this stage of his career, he knows this course inside out." },
      { name: "Alex Noren", odds: "175/1", fact: "Swedish veteran who has always been an accurate ball-striker. Augusta rewards accuracy and experience — Noren has plenty of both." },
      { name: "Harry Hall", odds: "175/1", fact: "English Tour player in his prime years. His steady game is more likely to result in a top-30 than a top-5, but making the weekend would be a solid result." },
      { name: "Nicolas Echavarria", odds: "175/1", fact: "Colombian with impressive Tour credentials. His recent form suggests he belongs at this level — Augusta will be the ultimate examination." },
      { name: "Sami Valimaki", odds: "225/1", fact: "Finnish European Tour player who earned his place in the field. A debut at Augusta is the experience of a lifetime — the cut will be his realistic ambition." },
    ]
  },
  {
    name: "The Miracles", color: "#3B6D11",
    g: [
      { name: "Nick Taylor", odds: "225/1", fact: "Canadian who famously holed out on the 72nd hole to win the Canadian Open. Miracle moments define him — and at 225/1, he needs another one at Augusta." },
      { name: "Sergio Garcia", odds: "225/1", fact: "The 2017 Masters champion who knows exactly how to win at Augusta. He's older now but still capable — and he has unparalleled Amen Corner experience." },
      { name: "Carlos Ortiz", odds: "225/1", fact: "Mexican Tour winner who brings solid driving and a calm temperament. A long shot, but his accurate tee-to-green game gives him a chance to make the cut." },
      { name: "Kristoffer Reitan", odds: "250/1", fact: "Young Scandinavian with a promising Tour record. Augusta is likely too soon but these long odds reflect upside potential if he clicks for four rounds." },
      { name: "Matt McCarty", odds: "250/1", fact: "Tour winner with a solid but unspectacular game. A cut would be the realistic target — anything beyond that edges into genuine miracle territory." },
      { name: "Rasmus Neergaard-Petersen", odds: "250/1", fact: "Danish emerging talent making his Augusta debut. His ball-striking is the foundation of his game — that at least gives him a chance to survive the cut." },
      { name: "Andrew Novak", odds: "250/1", fact: "Tour player with a grinder's mentality and solid statistics. He won't overpower Augusta but might just grind his way to a respectable finish." },
      { name: "Aldrich Potgieter", odds: "250/1", fact: "South African prodigy who hits it an extraordinary distance. At just 20, he's raw — but power is never wasted at Augusta and he could spring a surprise." },
      { name: "Tom McKibbin", odds: "250/1", fact: "Northern Irish prospect who has been impressive on the European Tour. A protegeé of Rory's management team — the comparisons are unfair but the talent is real." },
      { name: "Michael Brennan", odds: "350/1", fact: "Tour player who has earned his place the hard way. A 350/1 shot means you're hoping for lightning to strike — but someone has to be the long-odds story." },
      { name: "Michael Kim", odds: "350/1", fact: "Tour winner with solid credentials but someone who has never quite fulfilled his early promise. Augusta's demands are immense — he'll need his best week." },
      { name: "Davis Riley", odds: "500/1", fact: "Solid Tour player who has been quietly improving. 500/1 means you're dreaming — but golfers at these prices do occasionally make the cut and cause chaos." },
      { name: "Bubba Watson", odds: "500/1", fact: "Two-time Masters champion in 2012 and 2014. The famous hook around the trees at 10 in a playoff is Augusta legend. His best days may be behind him but never rule out a Watson at Augusta." },
      { name: "John Keefer", odds: "500/1", fact: "Making up the numbers? Not necessarily. Keefer has Tour credentials and on a good week anyone can go low at Augusta. Someone has to be the 500/1 surprise." },
      { name: "Zach Johnson", odds: "500/1", fact: "Two-time major champion (Masters 2007, Open 2015) and Ryder Cup captain. A sentimental pick whose Augusta pedigree means he can never be fully written off." },
    ]
  },
  {
    name: "The No Chancers", color: "#7F77DD",
    g: [
      { name: "Charl Schwartzel", odds: "750/1", fact: "The 2011 Masters champion who birdied the last four holes to win. His Augusta history is the stuff of legend — at 750/1 you're backing a fairytale." },
      { name: "Angel Cabrera", odds: "1000/1", fact: "The 2009 Masters champion. Cabrera's story is complicated but his Augusta pedigree is undeniable. You're not backing form here — you're backing history." },
      { name: "Mason Howell", odds: "1000/1", fact: "Making his major debut. The experience of playing Augusta National will last a lifetime. A cut would be a career-defining achievement." },
      { name: "Fifa Laopakdee", odds: "1000/1", fact: "Thai golfer making his Masters appearance. Augusta has global reach and every nation's representative gets their moment in the sun on the first tee." },
      { name: "Ethan Fang", odds: "1000/1", fact: "Young American talent still developing his game. Augusta is the ultimate finishing school — even not making the cut will teach him more than a Tour win elsewhere." },
      { name: "Brian Campbell", odds: "1000/1", fact: "Making his Augusta debut. The 1000/1 odds tell you everything about realistic expectations — but in this column, you're buying a ticket to dream." },
      { name: "Vijay Singh", odds: "1000/1", fact: "The 2000 Masters champion. Vijay is well into his 60s but past champions get to compete for life. A living legend, even if the scoreboard won't reflect it." },
      { name: "Jose Maria Olazabal", odds: "1000/1", fact: "Two-time Masters champion (1994, 1999) making a ceremonial appearance. Olazabal walking Augusta again is the story — the scorecard is irrelevant." },
      { name: "Brandon Holtz", odds: "1000/1", fact: "Tour debutant at Augusta. The nerves of teeing it up at Augusta National for the first time are unlike anything else in sport. Good luck to him." },
      { name: "Naoyuki Kataoka", odds: "1000/1", fact: "Japanese representative adding international flavour to the field. Augusta's global diversity is one of its great qualities — Kataoka carries a nation's hopes." },
      { name: "Danny Willett", odds: "1000/1", fact: "The 2016 Masters champion who famously benefited from Jordan Spieth's Amen Corner meltdown. Lightning rarely strikes twice but you never forget how to win here." },
      { name: "Jackson Herrington", odds: "1000/1", fact: "Amateur or recent qualifier who has earned the right to tee it up alongside the world's best. Augusta doesn't care about rankings on Thursday morning." },
      { name: "Fred Couples", odds: "1000/1", fact: "The 1992 Masters champion whose ball famously stayed on the bank at the 12th. Freddie at Augusta is pure nostalgia — and the crowds will adore every shot." },
      { name: "Mateo Pulcini", odds: "1000/1", fact: "Making his Augusta debut. In the No Chancers column but everyone was a no-chancer once. Enjoy the ride, Mateo." },
      { name: "Mike Weir", odds: "1000/1", fact: "The 2003 Masters champion — the only Canadian ever to win a major. A past champion appearance at Augusta is always special, whatever the scorecard says." },
    ]
  }
]
